const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');const scoreEl=document.getElementById('score');const streakEl=document.getElementById('streak');const leftEl=document.getElementById('left');const powerupEl=document.getElementById('powerup');const powerFill=document.getElementById('powerFill');const powerText=document.getElementById('powerText');const startScreen=document.getElementById('startScreen');const gameOver=document.getElementById('gameOver');const finalScore=document.getElementById('finalScore');const startBtn=document.getElementById('startBtn');const restartBtn=document.getElementById('restartBtn');
let W=1280,H=720,dpr=1,running=false,last=0,charging=false,charge=0,score=0,streak=0,shotActive=false,shotPocketed=0;let mouse={x:W*.25,y:H*.5};let balls=[],particles=[],rings=[];let powerup={type:'none',shots:0};const table={x:120,y:105,w:1040,h:510,rail:30,pocketR:30};const colors=['#52f5ff','#ff4bd8','#ffe55b','#8d6cff','#ff795b','#62ff98','#ff3e69'];
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(r.width*dpr);canvas.height=Math.floor(r.height*dpr);W=r.width;H=r.height;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const rand=(a,b)=>a+Math.random()*(b-a);const mag=(x,y)=>Math.hypot(x,y);
function pockets(){const x=table.x,y=table.y,w=table.w,h=table.h;return[{x,y},{x:x+w/2,y:y-2,bonus:true},{x:x+w,y},{x,y:y+h},{x:x+w/2,y:y+h+2,bonus:true},{x:x+w,y:y+h}]}
function makeBall(x,y,color,label,cue=false){return{x,y,vx:0,vy:0,r:cue?14:15,color,label,cue,pocketed:false,glow:0}}
function rack(){balls=[];const cy=table.y+table.h/2;balls.push(makeBall(table.x+table.w*.25,cy,'#fff','',true));let n=0;const startX=table.x+table.w*.69;for(let row=0;row<4;row++){for(let j=0;j<=row&&n<7;j++){const x=startX+row*28,y=cy-row*14+j*28;balls.push(makeBall(x,y,colors[n],String(n+1)));n++}}}
function reset(){score=0;streak=0;charge=0;charging=false;shotActive=false;shotPocketed=0;powerup={type:'none',shots:0};particles=[];rings=[];rack();updateHUD()}
function start(){reset();running=true;startScreen.classList.add('hidden');gameOver.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}startBtn.onclick=start;restartBtn.onclick=start;
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*(W/r.width);mouse.y=(e.clientY-r.top)*(H/r.height)});
canvas.addEventListener('mousedown',e=>{if(e.button!==0||!running||moving())return;charging=true;charge=Math.max(charge,.08)});
addEventListener('mouseup',e=>{if(e.button!==0||!charging||!running)return;charging=false;shoot()});
function cueBall(){return balls.find(b=>b.cue)}function moving(){return balls.some(b=>!b.pocketed&&mag(b.vx,b.vy)>.8)}
function shoot(){const c=cueBall();if(!c||c.pocketed)return;let dx=mouse.x-c.x,dy=mouse.y-c.y,l=mag(dx,dy)||1;dx/=l;dy/=l;const p=clamp(charge,.08,1);let speed=520+880*p;if(powerup.type==='power'){speed*=1.35;powerup.shots--}c.vx=dx*speed;c.vy=dy*speed;if(powerup.type==='ghost'){c.ghost=1.4;powerup.shots--}charge=0;shotActive=true;shotPocketed=0;burst(c.x,c.y,'#fff',18,1.2);if(powerup.shots<=0)powerup={type:'none',shots:0};updateHUD()}
function update(dt){if(charging&&!moving())charge=clamp(charge+dt*.72,0,1);powerFill.style.width=(charge*100)+'%';powerText.textContent=Math.round(charge*100)+'%';for(const b of balls){if(b.pocketed)continue;if(b.ghost)b.ghost=Math.max(0,b.ghost-dt);b.x+=b.vx*dt;b.y+=b.vy*dt;const drag=Math.pow(.16,dt);b.vx*=drag;b.vy*=drag;if(mag(b.vx,b.vy)<3){b.vx=0;b.vy=0}rail(b);checkPocket(b)}collisions();for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.12,dt);p.vy*=Math.pow(.12,dt);p.life-=dt}particles=particles.filter(p=>p.life>0);for(const r of rings){r.r+=250*dt;r.life-=dt}rings=rings.filter(r=>r.life>0);if(shotActive&&!moving()){shotActive=false;if(shotPocketed===0)streak=0;else maybePowerup();updateHUD();if(leftCount()===0){running=false;finalScore.textContent=score.toLocaleString();gameOver.classList.remove('hidden')}}}
function rail(b){const L=table.x+table.rail,R=table.x+table.w-table.rail,T=table.y+table.rail,B=table.y+table.h-table.rail;if(b.x-b.r<L){b.x=L+b.r;b.vx=Math.abs(b.vx)*.9;impact(b.x,b.y,b.color)}if(b.x+b.r>R){b.x=R-b.r;b.vx=-Math.abs(b.vx)*.9;impact(b.x,b.y,b.color)}if(b.y-b.r<T){b.y=T+b.r;b.vy=Math.abs(b.vy)*.9;impact(b.x,b.y,b.color)}if(b.y+b.r>B){b.y=B-b.r;b.vy=-Math.abs(b.vy)*.9;impact(b.x,b.y,b.color)}}
function collisions(){for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.pocketed||b.pocketed||a.ghost>0)continue;let dx=b.x-a.x,dy=b.y-a.y,d=mag(dx,dy),min=a.r+b.r;if(!d||d>=min)continue;let nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){const imp=rv*.98;a.vx+=imp*nx;a.vy+=imp*ny;b.vx-=imp*nx;b.vy-=imp*ny;impact((a.x+b.x)/2,(a.y+b.y)/2,b.color)}}}
function checkPocket(b){for(const p of pockets()){if(mag(b.x-p.x,b.y-p.y)<table.pocketR+5){if(b.cue){b.x=table.x+table.w*.25;b.y=table.y+table.h/2;b.vx=b.vy=0;score=Math.max(0,score-250);streak=0;rings.push({x:p.x,y:p.y,r:18,life:.45,color:'#ff3e69'});return}b.pocketed=true;b.vx=b.vy=0;streak++;shotPocketed++;let gain=500*streak;if(p.bonus)gain*=2;score+=gain;burst(p.x,p.y,b.color,32,2);rings.push({x:p.x,y:p.y,r:20,life:.6,color:p.bonus?'#ffe55b':b.color});return}}}
function maybePowerup(){if(streak<2||Math.random()>.48)return;const types=['power','ghost','multiball'];const t=types[Math.floor(Math.random()*types.length)];if(t==='multiball'){score+=1500;powerup={type:'none',shots:0};rings.push({x:W/2,y:H/2,r:20,life:.8,color:'#ff4bd8'})}else powerup={type:t,shots:1}}
function leftCount(){return balls.filter(b=>!b.cue&&!b.pocketed).length}
function updateHUD(){scoreEl.textContent=score.toLocaleString();streakEl.textContent=streak;leftEl.textContent=leftCount();powerupEl.textContent=powerup.type==='power'?'POWER SHOT':powerup.type==='ghost'?'GHOST SHOT':powerup.type==='none'?'NONE':powerup.type.toUpperCase()}
function draw(){ctx.clearRect(0,0,W,H);drawBg();drawTable();drawAim();drawBalls();drawFx()}
function drawBg(){const g=ctx.createRadialGradient(W/2,H/2,20,W/2,H/2,W*.7);g.addColorStop(0,'#161143');g.addColorStop(.5,'#07091c');g.addColorStop(1,'#010208');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(120,210,255,.35)';for(let i=0;i<90;i++)ctx.fillRect((i*137)%W,(i*83)%H,1,1)}
function drawTable(){ctx.save();ctx.shadowBlur=45;ctx.shadowColor='#5539ff';ctx.fillStyle='#120a24';roundRect(table.x-18,table.y-18,table.w+36,table.h+36,28);ctx.fill();ctx.shadowBlur=28;ctx.shadowColor='#13e7ff';const g=ctx.createLinearGradient(table.x,table.y,table.x+table.w,table.y+table.h);g.addColorStop(0,'#063944');g.addColorStop(.48,'#082e42');g.addColorStop(1,'#2b0d42');ctx.fillStyle=g;roundRect(table.x,table.y,table.w,table.h,20);ctx.fill();ctx.strokeStyle='rgba(96,245,255,.45)';ctx.lineWidth=3;ctx.stroke();for(const p of pockets()){ctx.beginPath();ctx.fillStyle='#010208';ctx.shadowBlur=p.bonus?32:14;ctx.shadowColor=p.bonus?'#ffe55b':'#ff4bd8';ctx.arc(p.x,p.y,table.pocketR,0,Math.PI*2);ctx.fill();ctx.lineWidth=p.bonus?5:2;ctx.strokeStyle=p.bonus?'#ffe55b':'#a854ff';ctx.stroke()}ctx.restore()}
function drawAim(){const c=cueBall();if(!running||!c||c.pocketed||moving())return;let dx=mouse.x-c.x,dy=mouse.y-c.y,l=mag(dx,dy)||1;dx/=l;dy/=l;ctx.save();ctx.setLineDash([10,10]);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(c.x+dx*330,c.y+dy*330);ctx.stroke();ctx.setLineDash([]);const back=55+charge*70;ctx.strokeStyle=charge>.75?'#ffe55b':'#ff4bd8';ctx.lineWidth=7;ctx.shadowBlur=18;ctx.shadowColor=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(c.x-dx*(back+130),c.y-dy*(back+130));ctx.lineTo(c.x-dx*back,c.y-dy*back);ctx.stroke();ctx.restore()}
function drawBalls(){for(const b of balls){if(b.pocketed)continue;ctx.save();ctx.shadowBlur=22;ctx.shadowColor=b.color;const g=ctx.createRadialGradient(b.x-5,b.y-6,2,b.x,b.y,b.r*1.25);g.addColorStop(0,'#fff');g.addColorStop(.24,b.color);g.addColorStop(1,'#050510');ctx.fillStyle=g;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();if(!b.cue){ctx.fillStyle='#fff';ctx.font='800 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.label,b.x,b.y)}ctx.restore()}}
function drawFx(){ctx.save();ctx.globalCompositeOperation='lighter';for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.s,p.s)}for(const r of rings){ctx.globalAlpha=clamp(r.life/.8,0,1);ctx.strokeStyle=r.color;ctx.lineWidth=5;ctx.shadowBlur=24;ctx.shadowColor=r.color;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke()}ctx.restore();ctx.globalAlpha=1}
function impact(x,y,color){if(Math.random()<.45)burst(x,y,color,5,.5)}function burst(x,y,color,n=18,p=1){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=rand(60,230)*p,life=rand(.18,.6);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life,max:life,s:rand(2,6),color})}}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function loop(t){if(!running&&gameOver.classList.contains('hidden'))return;const dt=Math.min(.025,(t-last)/1000||0);last=t;if(running)update(dt);draw();requestAnimationFrame(loop)}
draw();